# Generated by Django 3.2.1 on 2022-09-29 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_image', models.ImageField(upload_to='media')),
                ('content', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
