# Generated by Django 3.2.1 on 2022-07-11 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20220711_0427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_orderd',
            new_name='is_ordered',
        ),
    ]
