# Generated by Django 3.2.1 on 2022-07-01 05:53

from django.db import migrations, models
import django.db.models.deletion
import products.models
import products.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('order', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['-order'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=products.models.download_media_location)),
                ('media', models.FileField(blank=True, null=True, storage=products.storage.ProtectedStorage, upload_to=products.models.download_media_location)),
                ('video_link', models.TextField(blank=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=9.99, max_digits=10)),
                ('inventory', models.IntegerField(default=0)),
                ('featured', models.BooleanField(default=False)),
                ('can_backorder', models.BooleanField(default=False)),
                ('requires_shipping', models.BooleanField(default=False)),
                ('is_digital', models.BooleanField(default=True)),
                ('image_size', models.CharField(max_length=20, null=True)),
                ('location', models.CharField(max_length=150, null=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellers.seller')),
            ],
        ),
        migrations.CreateModel(
            name='Feautured',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('products', models.ManyToManyField(blank=True, limit_choices_to={'active': True}, to='products.Product')),
            ],
            options={
                'verbose_name': 'Featured',
                'verbose_name_plural': 'Featured',
            },
        ),
        migrations.CreateModel(
            name='CategoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/image')),
                ('title', models.CharField(blank=True, max_length=120, null=True)),
                ('feautured_image', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='products',
            field=models.ManyToManyField(to='products.Product'),
        ),
    ]
